lang: ja

project:
  render:
    - index.qmd
    - cv.qmd

website:
  navbar:
    left:
      - href: index.qmd
        text: ホーム
      - href: cv.qmd
        text: 略歴
    right:
      - text: EN
        href: /en/index.html
