lang: en

project:
  render:
    - en/index.qmd
    - en/cv.qmd

website:
  navbar:
    left:
      - href: /en/index.qmd
        text: Home
      - href: /en/cv.qmd
        text: CV
    right:
      - text: JA
        href: /index.html
